"""Analytic predictions and calculator equations."""

from lfm.formulas.masses import (
    angular_momentum_mass,
    down_quark_mass_ratio,
    higgs_w_mass_ratio,
    lepton_mass_ratio,
    mass_table,
    proton_mass_ratio,
    proton_mass_ratio_3gen,
    up_quark_mass_ratio,
    w_boson_mass_ratio,
    z_w_mass_ratio,
)
from lfm.formulas.predictions import (
    alpha_em,
    alpha_strong,
    beta0_qcd,
    mtheory_dimensions,
    muon_g2_anomaly,
    n_efoldings,
    n_generations,
    n_gluons,
    omega_lambda,
    omega_matter,
    predict_all,
    proton_electron_ratio_3gen,
    sin2_theta_w,
    spacetime_dimensions,
    string_dimensions,
    tau_muon_ratio,
    z_recombination,
)

__all__ = [
    # predictions
    "predict_all",
    "alpha_em",
    "alpha_strong",
    "sin2_theta_w",
    "omega_lambda",
    "omega_matter",
    "n_efoldings",
    "z_recombination",
    "n_generations",
    "n_gluons",
    "muon_g2_anomaly",
    "beta0_qcd",
    "spacetime_dimensions",
    "string_dimensions",
    "mtheory_dimensions",
    "tau_muon_ratio",
    "proton_electron_ratio_3gen",
    # masses
    "angular_momentum_mass",
    "lepton_mass_ratio",
    "up_quark_mass_ratio",
    "down_quark_mass_ratio",
    "proton_mass_ratio",
    "proton_mass_ratio_3gen",
    "w_boson_mass_ratio",
    "z_w_mass_ratio",
    "higgs_w_mass_ratio",
    "mass_table",
]
