"""
LFM — Lattice Field Medium Physics Library
===========================================

Simulate the universe from two equations.

Quick start::

    import lfm

    sim = lfm.Simulation(lfm.SimulationConfig(grid_size=64))
    sim.place_soliton((32, 32, 32), amplitude=6.0)
    sim.equilibrate()
    sim.run(steps=2000)
    print(sim.metrics())
"""

__version__ = "1.4.2"

from lfm.analysis import (
    angular_momentum_density,
    charge_density,
    chi_statistics,
    classify_potential,
    collider_event_display,
    color_current_variance,
    color_variance,
    compute_impact_parameter,
    compute_metrics,
    confinement_proxy,
    continuity_residual,
    correlation_function,
    coulomb_interaction_energy,
    count_clusters,
    detect_collision_events,
    effective_metric_00,
    energy_components,
    energy_conservation_drift,
    find_apparent_horizon,
    find_peaks,
    fit_cornell,
    fit_coulomb,
    fit_power_law,
    fit_ringdown_series,
    fit_yukawa,
    flatten_trajectories,
    fluid_fields,
    flux_tube_profile,
    gravitational_potential,
    gravitational_wave_strain,
    gw_power,
    gw_quadrupole,
    halo_mass_function,
    horizon_mass,
    interior_mask,
    keplerian_velocity,
    list_sparc_galaxies,
    matter_power_spectrum,
    measure_chi_midpoint,
    measure_force,
    measure_separation,
    metric_perturbation,
    momentum_density,
    phase_coherence,
    phase_field,
    power_spectrum,
    precession_rate,
    project_field_onto_modes,
    radial_profile,
    relative_spread,
    rotation_curve,
    rotation_curve_fit,
    schwarzschild_chi,
    smoothed_color_variance,
    sparc_load,
    spinor_center_of_energy,
    # spinor analysis (Paper 048)
    spinor_density,
    spinor_interference_energy,
    spinor_sigma_x,
    spinor_sigma_y,
    spinor_sigma_z,
    split_frequency_bands,
    static_interaction_potential,
    string_tension,
    target_band_summary,
    time_dilation_factor,
    total_angular_momentum,
    total_energy,
    track_peaks,
    void_fraction,
    void_statistics,
    weak_parity_asymmetry,
    well_fraction,
)
from lfm.config import BoundaryType, ChiMode, FieldLevel, PhysicsScale, SimulationConfig
from lfm.config_presets import full_physics, gravity_em, gravity_only, spinor_field
from lfm.constants import (
    AGE_UNIVERSE_GYR,
    ALPHA_EM,
    ALPHA_S,
    BETA_0,
    CHI0,
    D_ST,
    DT_DEFAULT,
    DT_MOTION,
    E_AMPLITUDE_BY_GRID,
    EPSILON_CC,
    EPSILON_W,
    KAPPA,
    KAPPA_C,
    KAPPA_STRING,
    KAPPA_TUBE,
    LAMBDA_H,
    N_COLORS,
    N_EFOLDINGS,
    N_GENERATIONS,
    OBSERVABLE_RADIUS_PLANCK,
    OMEGA_LAMBDA,
    OMEGA_MATTER,
    PLANCK_LENGTH_M,
    PLANCK_TIME_SEC,
    RANK_SU3,
    SA_D,
    SA_GAMMA,
    SA_L,
    SIN2_THETA_W,
    TOTAL_RADIUS_LOWER_BOUND_PLANCK,
    Z2_COORD,
    D,
)
from lfm.core.backends import get_backend, gpu_available
from lfm.core.backends.remote_backend import configure_remote
from lfm.core.evolver import Evolver
from lfm.experiment import (
    DEFAULT_RINGDOWN_K_MODES,
    Barrier,
    CollisionResult,
    ContinuousSource,
    DetectorScreen,
    Dispersion,
    ExperimentConfig,
    ExperimentResult,
    Next5FalsificationResult,
    QNMProjectionResult,
    Slit,
    collision,
    dispersion,
    next5_falsification_projection_v2,
    qnm_mode_projection_check,
)
from lfm.fields import (
    apply_rotation_x,
    apply_rotation_z,
    boosted_soliton,
    disk_positions,
    disk_velocities,
    equilibrate_chi,
    equilibrate_from_fields,
    gaussian_soliton,
    gaussian_spinor,
    grid_positions,
    initialize_disk,
    place_solitons,
    poisson_solve_fft,
    seed_noise,
    sparse_positions,
    spherical_phase_source,
    tetrahedral_positions,
    uniform_chi,
    vortex_spinor,
    wave_kick,
)
from lfm.io.snapshots import load_snapshots, save_snapshots
from lfm.particles import (
    ANTI_B_ZERO,
    ANTI_BOTTOM_QUARK,
    ANTI_CHARM_QUARK,
    ANTI_D_ZERO,
    ANTI_DOWN_QUARK,
    ANTI_ELECTRON_NEUTRINO,
    ANTI_KAON_ZERO,
    ANTI_LAMBDA_B,
    ANTI_LAMBDA_BARYON,
    ANTI_LAMBDA_C,
    ANTI_MUON_NEUTRINO,
    ANTI_OMEGA_BARYON,
    ANTI_SIGMA_MINUS,
    ANTI_SIGMA_PLUS,
    ANTI_STRANGE_QUARK,
    ANTI_TAU_NEUTRINO,
    ANTI_TOP_QUARK,
    # New particle constants
    ANTI_UP_QUARK,
    ANTI_XI_C_MINUS,
    ANTI_XI_PLUS,
    ANTIMUON,
    ANTINEUTRON,
    ANTIPROTON,
    ANTITAU,
    B_MINUS,
    B_PLUS,
    B_ZERO,
    BOTTOM_QUARK,
    CHARM_QUARK,
    D_MINUS,
    D_PLUS,
    D_ZERO,
    DELTA_BARYON,
    DOWN_QUARK,
    ELECTRON,
    ELECTRON_NEUTRINO,
    ETA_MESON,
    ETA_PRIME,
    GLUON,
    HIGGS,
    J_PSI,
    K_STAR,
    KAON_MINUS,
    KAON_PLUS,
    KAON_ZERO,
    LAMBDA_B,
    LAMBDA_BARYON,
    LAMBDA_C,
    MUON,
    MUON_NEUTRINO,
    NEUTRON,
    OMEGA_BARYON,
    OMEGA_MESON,
    PARTICLES,
    PHI_MESON,
    PHOTON,
    PION_MINUS,
    PION_PLUS,
    PION_ZERO,
    POSITRON,
    PROTON,
    RHO_MESON,
    SIGMA_1385,
    SIGMA_MINUS,
    SIGMA_PLUS,
    STRANGE_QUARK,
    TAU,
    TAU_NEUTRINO,
    TOP_QUARK,
    UP_QUARK,
    UPSILON,
    W_MINUS,
    W_PLUS,
    XI_1530,
    XI_C_PLUS,
    XI_MINUS,
    Z_BOSON,
    # Existing helpers
    AtomState,
    CollisionSetup,
    MoleculeState,
    Particle,
    PlacedParticle,
    SolitonSolution,
    amplitude_for_particle,
    boost_fields,
    boost_soliton_solution,
    create_atom,
    create_collision,
    create_molecule,
    create_particle,
    create_two_particles,
    get_particle,
    measure_center_of_energy,
    measure_momentum_density,
    measure_velocity,
    nuclear_chi_well,
    relax_eigenmode,
    sigma_for_particle,
    solve_eigenmode,
    ylm_seed,
)
from lfm.planning import (
    FeasibilityReport,
    UseCaseName,
    assess_feasibility,
    estimate_memory_gb,
    scale_limit_note,
    use_case_preset,
)
from lfm.scenarios import (
    BodyType,
    CelestialBody,
    black_hole_system,
    galaxy_core,
    place_bodies,
    solar_system,
)
from lfm.simulation import Simulation
from lfm.sweep import sweep, sweep_2d
from lfm.units import CosmicScale, PlanckScale
from lfm.viz.celestial import animate_celestial_3d
from lfm.viz.collision import animate_collision_3d
from lfm.viz.quantum import animate_3d_slices, animate_double_slit_3d
from lfm.core.stencils import laplacian_7pt, laplacian_19pt, laplacian_27pt

__all__ = [
    "__version__",
    # Constants
    "CHI0",
    "D",
    "D_ST",
    "KAPPA",
    "KAPPA_C",
    "KAPPA_STRING",
    "KAPPA_TUBE",
    "LAMBDA_H",
    "EPSILON_W",
    "EPSILON_CC",
    "ALPHA_S",
    "ALPHA_EM",
    "OMEGA_LAMBDA",
    "OMEGA_MATTER",
    "SIN2_THETA_W",
    "N_COLORS",
    "N_GENERATIONS",
    "N_EFOLDINGS",
    "DT_DEFAULT",
    "DT_MOTION",
    "E_AMPLITUDE_BY_GRID",
    # S_a v16 constants
    "SA_GAMMA",
    "SA_L",
    "SA_D",
    "BETA_0",
    "Z2_COORD",
    "RANK_SU3",
    # Cosmological scale
    "AGE_UNIVERSE_GYR",
    "OBSERVABLE_RADIUS_PLANCK",
    "TOTAL_RADIUS_LOWER_BOUND_PLANCK",
    "PLANCK_TIME_SEC",
    "PLANCK_LENGTH_M",
    # Config
    "SimulationConfig",
    "FieldLevel",
    "BoundaryType",
    "PhysicsScale",
    "ChiMode",
    # Config presets
    "gravity_only",
    "gravity_em",
    "full_physics",
    "spinor_field",
    # Backends & Simulation
    "Evolver",
    "Simulation",
    "get_backend",
    "gpu_available",
    "configure_remote",
    # Fields
    "gaussian_soliton",
    "gaussian_spinor",
    "vortex_spinor",
    "apply_rotation_x",
    "apply_rotation_z",
    "place_solitons",
    "wave_kick",
    "poisson_solve_fft",
    "equilibrate_chi",
    "equilibrate_from_fields",
    "seed_noise",
    "uniform_chi",
    "tetrahedral_positions",
    "sparse_positions",
    "spherical_phase_source",
    "grid_positions",
    "disk_positions",
    "disk_velocities",
    "initialize_disk",
    # Experiment components
    "Barrier",
    "Slit",
    "DetectorScreen",
    "ContinuousSource",
    "Dispersion",
    "dispersion",
    "collision",
    "CollisionResult",
    "qnm_mode_projection_check",
    "QNMProjectionResult",
    "next5_falsification_projection_v2",
    "Next5FalsificationResult",
    "DEFAULT_RINGDOWN_K_MODES",
    "ExperimentConfig",
    "ExperimentResult",
    # Planning
    "FeasibilityReport",
    "UseCaseName",
    "estimate_memory_gb",
    "assess_feasibility",
    "use_case_preset",
    "scale_limit_note",
    # Analysis
    "energy_components",
    "total_energy",
    "energy_conservation_drift",
    "chi_statistics",
    "well_fraction",
    "void_fraction",
    "count_clusters",
    "interior_mask",
    "compute_metrics",
    # Observables
    "radial_profile",
    "find_peaks",
    "fit_power_law",
    "keplerian_velocity",
    "measure_separation",
    "measure_force",
    "momentum_density",
    "rotation_curve",
    "rotation_curve_fit",
    "weak_parity_asymmetry",
    "confinement_proxy",
    "fluid_fields",
    "continuity_residual",
    # SPARC galaxy data
    "sparc_load",
    "list_sparc_galaxies",
    # Color / Confinement
    "color_variance",
    "smoothed_color_variance",
    "color_current_variance",
    "flux_tube_profile",
    "measure_chi_midpoint",
    "string_tension",
    "classify_potential",
    "fit_cornell",
    "fit_coulomb",
    "fit_yukawa",
    "static_interaction_potential",
    # Ringdown extraction
    "fit_ringdown_series",
    "project_field_onto_modes",
    "relative_spread",
    "split_frequency_bands",
    "target_band_summary",
    # Spectrum & Tracker
    "power_spectrum",
    "track_peaks",
    "flatten_trajectories",
    "detect_collision_events",
    "compute_impact_parameter",
    "collider_event_display",
    # Metric (spacetime geometry)
    "effective_metric_00",
    "metric_perturbation",
    "time_dilation_factor",
    "gravitational_potential",
    "schwarzschild_chi",
    "find_apparent_horizon",
    "horizon_mass",
    # Phase (EM / charge)
    "phase_field",
    "charge_density",
    "phase_coherence",
    "coulomb_interaction_energy",
    # Angular momentum
    "angular_momentum_density",
    "total_angular_momentum",
    "precession_rate",
    # Cosmological statistics
    "correlation_function",
    "matter_power_spectrum",
    "halo_mass_function",
    "void_statistics",
    # Gravitational waves
    "gravitational_wave_strain",
    "gw_quadrupole",
    "gw_power",
    # Spinor (Paper 048)
    "spinor_density",
    "spinor_sigma_z",
    "spinor_sigma_x",
    "spinor_sigma_y",
    "spinor_interference_energy",
    "spinor_center_of_energy",
    # Boosted soliton
    "boosted_soliton",
    # Sweep
    "sweep",
    "sweep_2d",
    # Units
    "CosmicScale",
    "PlanckScale",
    # Snapshot I/O
    "save_snapshots",
    "load_snapshots",
    # Visualization
    "animate_3d_slices",
    "animate_celestial_3d",
    "animate_collision_3d",
    "animate_double_slit_3d",
    # Particle catalog (Phase 1)
    "Particle",
    "PARTICLES",
    "get_particle",
    "amplitude_for_particle",
    "sigma_for_particle",
    "ELECTRON",
    "POSITRON",
    "MUON",
    "ANTIMUON",
    "TAU",
    "ANTITAU",
    "UP_QUARK",
    "DOWN_QUARK",
    "STRANGE_QUARK",
    "CHARM_QUARK",
    "PROTON",
    "ANTIPROTON",
    "NEUTRON",
    "ANTINEUTRON",
    "PHOTON",
    # Antiquarks
    "ANTI_UP_QUARK",
    "ANTI_DOWN_QUARK",
    "ANTI_STRANGE_QUARK",
    "ANTI_CHARM_QUARK",
    # Heavy quarks
    "BOTTOM_QUARK",
    "ANTI_BOTTOM_QUARK",
    "TOP_QUARK",
    "ANTI_TOP_QUARK",
    # Neutrinos
    "ELECTRON_NEUTRINO",
    "ANTI_ELECTRON_NEUTRINO",
    "MUON_NEUTRINO",
    "ANTI_MUON_NEUTRINO",
    "TAU_NEUTRINO",
    "ANTI_TAU_NEUTRINO",
    # Gauge Bosons
    "W_PLUS",
    "W_MINUS",
    "Z_BOSON",
    "GLUON",
    "HIGGS",
    # Light Mesons
    "PION_PLUS",
    "PION_MINUS",
    "PION_ZERO",
    "KAON_PLUS",
    "KAON_MINUS",
    "KAON_ZERO",
    "ANTI_KAON_ZERO",
    "ETA_MESON",
    "RHO_MESON",
    "OMEGA_MESON",
    "ETA_PRIME",
    "PHI_MESON",
    "K_STAR",
    # Charm Mesons
    "D_PLUS",
    "D_MINUS",
    "D_ZERO",
    "ANTI_D_ZERO",
    "J_PSI",
    # Bottom Mesons
    "B_PLUS",
    "B_MINUS",
    "B_ZERO",
    "ANTI_B_ZERO",
    "UPSILON",
    # Strange Baryons
    "LAMBDA_BARYON",
    "ANTI_LAMBDA_BARYON",
    "SIGMA_PLUS",
    "SIGMA_MINUS",
    "ANTI_SIGMA_PLUS",
    "ANTI_SIGMA_MINUS",
    "XI_MINUS",
    "ANTI_XI_PLUS",
    "OMEGA_BARYON",
    "ANTI_OMEGA_BARYON",
    "DELTA_BARYON",
    "SIGMA_1385",
    "XI_1530",
    # Heavy Baryons
    "LAMBDA_C",
    "ANTI_LAMBDA_C",
    "XI_C_PLUS",
    "ANTI_XI_C_MINUS",
    "LAMBDA_B",
    "ANTI_LAMBDA_B",
    # Phase 2: Eigenmode solver
    "SolitonSolution",
    "solve_eigenmode",
    # Phase 3: Relaxation solver + boost
    "relax_eigenmode",
    "ylm_seed",
    "boost_fields",
    # Phase 3: Particle motion
    "boost_soliton_solution",
    "measure_center_of_energy",
    "measure_momentum_density",
    "measure_velocity",
    # Phase 4: Composite systems
    "AtomState",
    "MoleculeState",
    "nuclear_chi_well",
    "create_atom",
    "create_molecule",
    # Phase 5: Factory
    "PlacedParticle",
    "create_particle",
    "create_two_particles",
    # Phase 6: Collision
    "CollisionSetup",
    "create_collision",
    # Celestial scenarios
    "BodyType",
    "CelestialBody",
    "solar_system",
    "black_hole_system",
    "galaxy_core",
    "place_bodies",
    # Laplacian stencils
    "laplacian_7pt",
    "laplacian_19pt",
    "laplacian_27pt",
]
