"""
lfm.particles — Particle Catalog and Eigenmode Solver
======================================================

Provides the particle specification dataclass, the canonical particle
table, helper functions for simulation parameters, and (Phase 2) the
SCF eigenmode solver.

Quick usage::

    from lfm.particles import ELECTRON, MUON, PROTON
    from lfm.particles import get_particle, amplitude_for_particle

    p = get_particle("muon")
    amp = amplitude_for_particle(p, N=64)
"""

from lfm.particles.catalog import (
    ANTIMUON,
    ANTINEUTRON,
    ANTIPROTON,
    ANTITAU,
    ANTI_B_ZERO,
    ANTI_BOTTOM_QUARK,
    ANTI_CHARM_QUARK,
    ANTI_D_ZERO,
    ANTI_DOWN_QUARK,
    ANTI_ELECTRON_NEUTRINO,
    ANTI_KAON_ZERO,
    ANTI_LAMBDA_B,
    ANTI_LAMBDA_BARYON,
    ANTI_LAMBDA_C,
    ANTI_MUON_NEUTRINO,
    ANTI_OMEGA_BARYON,
    ANTI_SIGMA_MINUS,
    ANTI_SIGMA_PLUS,
    ANTI_STRANGE_QUARK,
    ANTI_TAU_NEUTRINO,
    ANTI_TOP_QUARK,
    ANTI_UP_QUARK,
    ANTI_XI_C_MINUS,
    ANTI_XI_PLUS,
    B_MINUS,
    B_PLUS,
    B_ZERO,
    BOTTOM_QUARK,
    CHARM_QUARK,
    D_MINUS,
    D_PLUS,
    D_ZERO,
    DOWN_QUARK,
    # Pre-defined particle constants
    ELECTRON,
    ELECTRON_NEUTRINO,
    ETA_MESON,
    GLUON,
    HIGGS,
    J_PSI,
    KAON_MINUS,
    KAON_PLUS,
    KAON_ZERO,
    LAMBDA_B,
    LAMBDA_BARYON,
    LAMBDA_C,
    MUON,
    MUON_NEUTRINO,
    NEUTRON,
    OMEGA_BARYON,
    PARTICLES,
    DELTA_BARYON,
    ETA_PRIME,
    K_STAR,
    OMEGA_MESON,
    PHI_MESON,
    PHOTON,
    PION_MINUS,
    PION_PLUS,
    PION_ZERO,
    POSITRON,
    PROTON,
    RHO_MESON,
    SIGMA_1385,
    SIGMA_MINUS,
    SIGMA_PLUS,
    XI_1530,
    STRANGE_QUARK,
    TAU,
    TAU_NEUTRINO,
    TOP_QUARK,
    UP_QUARK,
    UPSILON,
    W_MINUS,
    W_PLUS,
    XI_C_PLUS,
    XI_MINUS,
    Z_BOSON,
    Particle,
    amplitude_for_particle,
    get_particle,
    sigma_for_particle,
)
from lfm.particles.composite import (
    AtomState,
    MoleculeState,
    create_atom,
    create_molecule,
    nuclear_chi_well,
)
from lfm.particles.factory import (
    CollisionSetup,
    PlacedParticle,
    create_collision,
    create_particle,
    create_two_particles,
)
from lfm.particles.motion import (
    boost_soliton_solution,
    measure_center_of_energy,
    measure_momentum_density,
    measure_velocity,
)
from lfm.particles.solver import (
    SolitonSolution,
    boost_fields,
    relax_eigenmode,
    solve_eigenmode,
    ylm_seed,
)

__all__ = [
    "Particle",
    "PARTICLES",
    "get_particle",
    "amplitude_for_particle",
    "sigma_for_particle",
    # Leptons
    "ELECTRON",
    "POSITRON",
    "MUON",
    "ANTIMUON",
    "TAU",
    "ANTITAU",
    # Neutrinos
    "ELECTRON_NEUTRINO",
    "ANTI_ELECTRON_NEUTRINO",
    "MUON_NEUTRINO",
    "ANTI_MUON_NEUTRINO",
    "TAU_NEUTRINO",
    "ANTI_TAU_NEUTRINO",
    # Quarks
    "UP_QUARK",
    "DOWN_QUARK",
    "STRANGE_QUARK",
    "CHARM_QUARK",
    "BOTTOM_QUARK",
    "TOP_QUARK",
    # Antiquarks
    "ANTI_UP_QUARK",
    "ANTI_DOWN_QUARK",
    "ANTI_STRANGE_QUARK",
    "ANTI_CHARM_QUARK",
    "ANTI_BOTTOM_QUARK",
    "ANTI_TOP_QUARK",
    # Nucleons
    "PROTON",
    "ANTIPROTON",
    "NEUTRON",
    "ANTINEUTRON",
    # Gauge Bosons
    "PHOTON",
    "W_PLUS",
    "W_MINUS",
    "Z_BOSON",
    "GLUON",
    "HIGGS",
    # Light Mesons
    "PION_PLUS",
    "PION_MINUS",
    "PION_ZERO",
    "KAON_PLUS",
    "KAON_MINUS",
    "KAON_ZERO",
    "ANTI_KAON_ZERO",
    "ETA_MESON",
    "RHO_MESON",
    "OMEGA_MESON",
    "ETA_PRIME",
    "PHI_MESON",
    "K_STAR",
    # Charm Mesons
    "D_PLUS",
    "D_MINUS",
    "D_ZERO",
    "ANTI_D_ZERO",
    "J_PSI",
    # Bottom Mesons
    "B_PLUS",
    "B_MINUS",
    "B_ZERO",
    "ANTI_B_ZERO",
    "UPSILON",
    # Strange Baryons
    "LAMBDA_BARYON",
    "ANTI_LAMBDA_BARYON",
    "SIGMA_PLUS",
    "SIGMA_MINUS",
    "ANTI_SIGMA_PLUS",
    "ANTI_SIGMA_MINUS",
    "XI_MINUS",
    "ANTI_XI_PLUS",
    "OMEGA_BARYON",
    "ANTI_OMEGA_BARYON",
    "DELTA_BARYON",
    "SIGMA_1385",
    "XI_1530",
    # Heavy Baryons
    "LAMBDA_C",
    "ANTI_LAMBDA_C",
    "XI_C_PLUS",
    "ANTI_XI_C_MINUS",
    "LAMBDA_B",
    "ANTI_LAMBDA_B",
    # Phase 2: Eigenmode solver
    "SolitonSolution",
    "solve_eigenmode",
    # Phase 3: Relaxation solver + boost
    "relax_eigenmode",
    "ylm_seed",
    "boost_fields",
    # Phase 3: Particle motion
    "boost_soliton_solution",
    "measure_center_of_energy",
    "measure_momentum_density",
    "measure_velocity",
    # Phase 4: Composite systems
    "AtomState",
    "MoleculeState",
    "nuclear_chi_well",
    "create_atom",
    "create_molecule",
    # Phase 5: Factory
    "PlacedParticle",
    "create_particle",
    "create_two_particles",
    # Phase 6: Collision
    "CollisionSetup",
    "create_collision",
]
