"""Foundational LFM revision candidates.

Modules in this package are executable research prototypes. They are not
part of the canonical two-register Simulation until an explicit promotion
gate updates that status.
"""

from lfm.foundations.r3_link_frame import (
    R3_ACTION_ID,
    R3_REGISTER_ID,
    R3LinkFrameParameters,
    R3ProductLink,
    chiral_frame_curvature,
    frame_shape_acceleration,
    internal_covariant_difference,
    product_plaquette_energy,
    r3_action_declaration,
    r3_action_fingerprint,
    transform_internal_matter,
    transform_product_link,
)
from lfm.foundations.r3_link_frame_live import (
    R3_LIVE_ACTION_ID,
    R3_LIVE_REGISTER_ID,
    R3LiveParameters,
    R3LiveState,
    group_constraint_errors,
    potential_energy_and_rates,
    r3_live_action_declaration,
    r3_live_action_fingerprint,
    reverse_momenta,
    so4_generators,
    state_distance,
    step_r3_live,
    su3_generators,
    total_hamiltonian,
    triangle_loops,
)
from lfm.foundations.r4_unified_live import (
    R4_ACTION_ID,
    R4_REGISTER_ID,
    R4FrameScalarState,
    R4Parameters,
    R4State,
    color_dielectric,
    group_constraint_errors as r4_group_constraint_errors,
    potential_energy_and_rates as r4_potential_energy_and_rates,
    r4_action_declaration,
    r4_action_fingerprint,
    r4_frame_scalar_energy,
    reverse_momenta as reverse_r4_momenta,
    state_distance as r4_state_distance,
    step_r4,
    step_r4_frame_scalar,
    su2_generators,
    total_hamiltonian as r4_total_hamiltonian,
)
from lfm.foundations.r4_color_static import (
    R4ColorStaticState,
    R4FixedColorElectricState,
    color_gauss_divergence,
    r4_color_electric_site_density,
    r4_color_flux_observables,
    r4_color_incident_flux_sq,
    r4_color_static_energy,
    r4_color_vacuum_instability_flux_sq,
    relax_r4_color_static,
    relax_r4_chi_at_fixed_color_electric,
    solve_color_gauss_minimum,
)
from lfm.foundations.r4_quantum_color import (
    R4MagneticCompetitionBound,
    R4QuantumColorCoefficients,
    creutz_ratio_from_log_transfer,
    fundamental_flux_energy,
    log_wilson_transfer,
    local_su3_gauge_transform,
    minimum_link_distance,
    r4_magnetic_competition_bound,
    r4_quantum_color_coefficients,
    su3_fundamental_algebra_audit,
    weighted_loop_incidence,
)
from lfm.foundations.r4_gauge_spectrum import (
    directional_link_inertia,
    face_square_cycles,
    face_square_fourier_hessian,
    gauge_link_spectrum,
    oriented_cycle_fourier_coefficients,
    transverse_mode_speeds,
    triangle_fourier_hessian,
)
from lfm.foundations.r5_unified_live import (
    R5_ACTION_ID,
    R5_REGISTER_ID,
    R5Parameters,
    R5Rates,
    R5State,
    group_constraint_errors as r5_group_constraint_errors,
    kinetic_energy as r5_kinetic_energy,
    potential_energy_and_rates as r5_potential_energy_and_rates,
    r5_action_declaration,
    r5_action_fingerprint,
    reverse_momenta as reverse_r5_momenta,
    state_distance as r5_state_distance,
    step_r5,
    total_hamiltonian as r5_total_hamiltonian,
    vacuum_state as r5_vacuum_state,
)
from lfm.foundations.r5_u1_static import (
    R5U1StaticState,
    periodic_point_pair_charge,
    solve_u1_gauss_minimum,
)
from lfm.foundations.r6_unified_live import (
    R6_ACTION_ID,
    R6_REGISTER_ID,
    R6Parameters,
    R6R4Parameters,
    R6Rates,
    R6State,
    group_constraint_errors as r6_group_constraint_errors,
    kinetic_energy as r6_kinetic_energy,
    potential_energy_and_rates as r6_potential_energy_and_rates,
    r6_action_declaration,
    r6_action_fingerprint,
    reverse_momenta as reverse_r6_momenta,
    state_distance as r6_state_distance,
    step_r6,
    total_hamiltonian as r6_total_hamiltonian,
    vacuum_state as r6_vacuum_state,
)

__all__ = [
    "R3_ACTION_ID",
    "R3_REGISTER_ID",
    "R3LinkFrameParameters",
    "R3ProductLink",
    "internal_covariant_difference",
    "transform_internal_matter",
    "transform_product_link",
    "chiral_frame_curvature",
    "product_plaquette_energy",
    "frame_shape_acceleration",
    "r3_action_declaration",
    "r3_action_fingerprint",
    "R3_LIVE_ACTION_ID",
    "R3_LIVE_REGISTER_ID",
    "R3LiveParameters",
    "R3LiveState",
    "group_constraint_errors",
    "potential_energy_and_rates",
    "r3_live_action_declaration",
    "r3_live_action_fingerprint",
    "reverse_momenta",
    "so4_generators",
    "state_distance",
    "step_r3_live",
    "su3_generators",
    "total_hamiltonian",
    "triangle_loops",
    "R4_ACTION_ID",
    "R4_REGISTER_ID",
    "R4FrameScalarState",
    "R4Parameters",
    "R4State",
    "color_dielectric",
    "r4_group_constraint_errors",
    "r4_potential_energy_and_rates",
    "r4_action_declaration",
    "r4_action_fingerprint",
    "r4_frame_scalar_energy",
    "reverse_r4_momenta",
    "r4_state_distance",
    "step_r4",
    "step_r4_frame_scalar",
    "su2_generators",
    "r4_total_hamiltonian",
    "R4ColorStaticState",
    "R4FixedColorElectricState",
    "color_gauss_divergence",
    "r4_color_electric_site_density",
    "r4_color_flux_observables",
    "r4_color_incident_flux_sq",
    "r4_color_static_energy",
    "r4_color_vacuum_instability_flux_sq",
    "relax_r4_color_static",
    "relax_r4_chi_at_fixed_color_electric",
    "solve_color_gauss_minimum",
    "R4MagneticCompetitionBound",
    "R4QuantumColorCoefficients",
    "creutz_ratio_from_log_transfer",
    "fundamental_flux_energy",
    "log_wilson_transfer",
    "local_su3_gauge_transform",
    "minimum_link_distance",
    "r4_magnetic_competition_bound",
    "r4_quantum_color_coefficients",
    "su3_fundamental_algebra_audit",
    "weighted_loop_incidence",
    "directional_link_inertia",
    "face_square_cycles",
    "face_square_fourier_hessian",
    "gauge_link_spectrum",
    "oriented_cycle_fourier_coefficients",
    "transverse_mode_speeds",
    "triangle_fourier_hessian",
    "R5_ACTION_ID",
    "R5_REGISTER_ID",
    "R5Parameters",
    "R5Rates",
    "R5State",
    "r5_group_constraint_errors",
    "r5_kinetic_energy",
    "r5_potential_energy_and_rates",
    "r5_action_declaration",
    "r5_action_fingerprint",
    "reverse_r5_momenta",
    "r5_state_distance",
    "step_r5",
    "r5_total_hamiltonian",
    "r5_vacuum_state",
    "R5U1StaticState",
    "periodic_point_pair_charge",
    "solve_u1_gauss_minimum",
    "R6_ACTION_ID",
    "R6_REGISTER_ID",
    "R6Parameters",
    "R6R4Parameters",
    "R6Rates",
    "R6State",
    "r6_group_constraint_errors",
    "r6_kinetic_energy",
    "r6_potential_energy_and_rates",
    "r6_action_declaration",
    "r6_action_fingerprint",
    "reverse_r6_momenta",
    "r6_state_distance",
    "step_r6",
    "r6_total_hamiltonian",
    "r6_vacuum_state",
]
